name: Cybersecurity Chatbot CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  DOTNET_VERSION: '8.0.x'
  BUILD_CONFIGURATION: 'Release'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    # ----------------------------------
    # 1. Checkout code
    # ----------------------------------
    - name: Checkout repository
      uses: actions/checkout@v4

    # ----------------------------------
    # 2. Setup .NET
    # ----------------------------------
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # ----------------------------------
    # 3. Restore dependencies
    # ----------------------------------
    - name: Restore dependencies
      run: dotnet restore

    # ----------------------------------
    # 4. Build solution
    # ----------------------------------
    - name: Build solution
      run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

    # ----------------------------------
    # 5. Run tests
    # ----------------------------------
    - name: Run tests
      run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --verbosity normal

    # ----------------------------------
    # 6. Publish artifacts
    # ----------------------------------
    - name: Publish application
      run: dotnet publish -c ${{ env.BUILD_CONFIGURATION }} -o ./publish

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: chatbot-build
        path: ./publish/**/*
